youtubevideodownloader_app/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'ytproject'

urlpatterns = [
    path('login', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout, name='logout'),
    path('video_download', views.video_download, name='video_download'),
    path('audio_download', views.audio_download, name='audio_download'),
    path('done', views.done, name='done'),
    path('', views.main, name='main'),
    
    path('reset_password', auth_views.PasswordResetView.as_view(template_name="templates/reset_password.html"), name='reset_password'),
    
    path('reset_password_done', auth_views.PasswordResetDoneView.as_view(template_name="templates/reset_password_done.html"), name='password_reset_done'),
    
    path('reset/<uidb64>/<token>', auth_views.PasswordResetView.as_view(), name='password_reset_confirm'),
    
    path('reset_password_complete', auth_views.PasswordResetView.as_view(template_name="templates/reset_password_complete.html"), name='password_reset_complete'),
]

youtubevideodownloader_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('youtubevideodownloader_app.urls')),
]

youtubevideodownloader_app/models.py
from django.db import models

youtubevideodownloader_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, auth
from django.contrib import messages
from pytube import YouTube
import os
from django.contrib import messages


# Create your views here.

def main(request):
    return render(request, 'main.html')

def video_download(request):
    global url 
    url = request.GET.get('url')
    yt = YouTube(url)
    video = []
    video = yt.streams.filter(progressive=True).all()
    print(video)
    embed_link = url.replace("watch?v=", "embed/")
    Title = "[dev_Max youtube downloader] " + yt.title
    context = {'video':video, 'embed':embed_link, 'title':Title}
    
    return render(request, 'video_download.html', context)


def audio_download(request):
    global url
    ytd = YouTube(url)
    audio = []
    ytd.streams.filter(only_audio=True)
    Title = ytd.title
    context2 = {'audio':audio, 'title':Title}
    return render(request, "audio_download.html", context2)

def done(request, resolution):
    global url 
    homedir = os.path.expanduser("~")
    dirs = homedir + '/Downloads'
    if request.method == "POST":
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request, 'done.html')
    else:
        messages.info("Your download is taking too long to respond. Try again") 
        return render(request, 'done.html')
    

def login(request): 
   if request.method == 'POST':
       username = request.POST['username']
       password = request.POST['password']
       
       user = auth.authenticate(username=username, password=password)
       
       if user is not None:
           auth.login(request, user)
           return redirect('/')
       
       else:
           messages.info(request, 'Invalid credentials')
           return redirect('login')
   else: 
        return render(request, 'login.html')  
    
def logout(request):
    auth.logout(request)
    return redirect('/')    
    
       
    

def signup(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        
        if User.objects.filter(email=email,).exists():
            messages.info(request, 'Email already used')
            return redirect('signup')
        
        elif User.objects.filter(username=username,).exists():
            messages.info(request, 'Username already taken')
            return redirect('signup')
            
        else: 
            user = User.objects.create_user(email=email, username=username, password=password)
            user.save();
            messages.info(request, 'Account successfuly created')
            return redirect('signup')
    
    else:
        return render(request, 'signup.html')
    

templates/audio_download.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download video</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" a href="{% static 'css/bootstrap.css' %}" />

</head>

<body class="body">
<center>
    <div id="d-container">
      <div class="container-box">

       <div id="video_description_box">
          <h2>{{title}}</h2> 
          <div id="video">
          <div class="ratio ratio-16x9">
              <iframe id="embed-item" src="{{embed}}" title="YouTube video" allowfullscreen></iframe>
            </div>
          </div>
       </div>

       <div id="download_message_info">
         {% for message in messages %}
         <h3>{{message}}</h3>
           
         {% endfor %}
        </div>

        <div id="download_video_box">
              <table class="table caption-top">
                <caption>Your audio is ready..</caption>
                <thead>
                  <tr>
                    <th scope="col" class="table_sections">Quality</th>
                    <th scope="col" class="table_sections">Download type</th>
                    <th scope="col" class="table_sections">File size</th>
                    <th scope="col" class="table_sections">Downloads</th>
                  </tr>
                </thead>

                <tbody>
                 {% for i in audio %}
                  <tr> 
                    <td class="table_sections">{{i.resolution}}</td>
                    <td class="table_sections">{{i.type}}</td>
                    <td class="table_sections">{{i.filesize}}</td>
                
                  
                    <form action="" method="POST">
                      {% csrf_token %}
                    <td class="table_sections"><button class="btn btn-success">Download</button></td>
                    </form>
                 {% endfor %}
                  </tr> 
                </tbody>
                
              </table>
        </div>

    <div id="box2" class="box">
      <h2>How do I download an audio file?</h2>
      <p>After your youtube link is processed the audio for your video will be converted, you should see a green button called Download. Click on it and check your downloads</p>
    </div>
    
    <div id="box1" class="box">
        <h2>Which type of audio will i get?</h2>
        <p>The type of audio you will get for the video is an mp4. If you want to change the audio type go to your files and rename to your desired audio file
          <br>
          <p>for example from .mp4 to .mp3</p>
        </p>
      </div>

      </div>
         
        </div>
    </div>
  
  </center>
<script src="{% static 'js/bootstrap.js/' %}>    
</body>
</html>

templates/done.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download done</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

    <div id="download_message_info">
        {% for message in messages %}
        <h3 id="msg">{{message}}</h3>
          
        {% endfor %}
       </div>
    
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

    <div>
        <h1>Login in your account</h1>
    <form action="login" method="POST">

        {% for message in messages %}
        <h3 id="msg">{{message}}</h3>
        {% endfor %}


        {% csrf_token %}
        <label>Username</label>
        <input type="text"  placeholder="" name="username">
        <label>Password</label>
        <input type="password" placeholder="" name="password">
        <button type="submit" id="btn">login </button>
    </form>
    <p> forgot password?<a href="{% url 'reset_password' %}">click here</a></p>
</div>
    
</body>
</html>

templates/main.html
<!DOCTYPE html>

<html lang="en">
     {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" a href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <title>Youtube_video_downloader</title>
</head>
<body class="body">
   <center>
    <div id="container">
      <div class="container-box">
         <div id="headingbox">
          <h1>Dev_Max Youtube Video Downloader</h1> 
         </div> 
          <h2>Search your video below </h2>

        <div id="contents">
          <form action="video_download" method="GET">
                <nav>
                   <form action="">
                      <input name="url" id="link"  class="form-control-mr-sm-2" type="url" placeholder="Input video link or name here" aria-label="Search">
                      <button id="btn-btn-primary" type="submit"><span class="material-symbols-outlined">search</span></button>
                      
                    </form>
                  </nav>
            </form>
        </div>

        <div id="items"> </div>


        <div id="description-box">

          <div id="box1" class="box">
          <h2>What is dev_Max Youtube Video Downloader?</h2>
          <p>This is the best website that enables you to download youtube videos and at the same time can convert you video to audio </p>
          </div>
          
          <br>

          <div id="box2" class="box">
            <h2>How do I download a video?</h2>
            <p>Go to youtube and copy the link of your youtube video link. After that paste the link in the input above. Click the button named "Search"</p>
          </div>
        </div>

      </div>
    </div>
  </center>
</body>
</html>

templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset_password</title>
</head>
<body>
    <center>
        <p>Forgot your password? Enter your email address below, and we'll email instructions for setting a new one</p>
             
        <form method="POST"><input type="hidden">

         {% csrf_token %}
         {{form}}

            <input type="submit" value="Reset my password">
        </form>
    </center>
    
</body>
</html>

templates/reset_password_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset_password_confirm</title>
</head>
<body>
    
   <center>
       <div>
        <h2>Password reset complete</h2>
    <h4>Your password has been set. You may go ahead and log in now.
        <br>
     <a href="{% url 'login'  %}">Log in</a>
    </h4>
    </div>
</center>
    
</body>
</html>

templates/reset_password_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>resetpassword</title>
</head>
<body>

<div>
    <center>
    <h3>Password reset sent <br><br>
        Hello We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
        
        If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
            
    </h3>
</center>
</div>
    
</body>
</html>

templates/signup.html
<!DOCTYPE html>
 {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div>
        <h1>Create account</h1>
    <form action="signup" method="POST">
        {% csrf_token %}

      {% for message in messages %}
      <h2 id="msg">{{message}}</h2>
      {% endfor %}
      
        <label>Email</label>
        <input type="email" placeholder="" name="email">
        <label>Username</label>
        <input type="text"  placeholder="" name="username">
        <label>Password</label>
        <input type="password" placeholder="" name="password">
        <label for="">Confirm password</label>
        <input type="password" placeholder="" name="password2">
        <button type="submit" > Signup </button>

    </form>
</div>
</body>
</html>

templates/video_download.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download video</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" a href="{% static 'css/bootstrap.css' %}" />

</head>

<body class="body">
<center>
    <div id="d-container">
      <div class="container-box">

       <div id="video_description_box">
          <h2>{{Title}}</h2> 
          <div id="video">
          <div class="ratio ratio-16x9">
              <iframe id="embed-item" src="{{embed}}" title="YouTube video" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        

        <div id="download_video_box">
              <table class="table caption-top">
                <caption>Your video is ready..</caption>
                <thead>
                  <tr>
                    <th scope="col" class="table_sections">Quality</th>
                    <th scope="col" class="table_sections">Download type</th>
                    <th scope="col" class="table_sections">File size</th>
                    <th scope="col" class="table_sections">Downloads</th>
                  </tr>
                </thead>

                <tbody>
                 {% for j in video %}
                  <tr> 
                    <td class="table_sections">{{j.resolution}}</td>
                    <td class="table_sections">{{j.type}}</td>
                    <td class="table_sections">{{j.filesize}}</td>
                
                  
                    <form action="{% url 'ytproject:done' j.resolution %}" method="POST">
                      {% csrf_token %}
                    <td class="table_sections"><button class="btn btn-success">Download</button></td>
                    </form>
                 {% endfor %}
                  </tr> 
                </tbody>
                
              </table>
              
              <div id="convertion_btn">
                  <form action="audio_download" method="POST" >
                    {% csrf_token %}
                  <td class="table_sections"><button  class="btn btn-primary">Get audio for the video</button></td>
                  </form>
              </div>

        </div>

       


    <div id="description-box">   
        <div id="box1" class="box">
          <h2>How do I download a video?</h2>
          <p>After your video link is processed, you should see a green button called Download. Click on it and check your downloads</p>
        </div>
    
    </div>
  
  </center>
<script src="{% static 'js/bootstrap.js/' %}>    
</body>
</html>